---@class PluginModule
---@field name? string
---@field enabled? boolean
---@field requires? string[]
---@field setup? fun()
---@field priority? integer
---@field lazy? string | PluginModule.Lazy

---@class PluginModule.Resolved
---@field name? string
---@field path? string
---@field setup? fun()
---@field priority? integer
---@field requires? string[]
---@field lazy? string | PluginModule.Lazy | false
---@field loaded? boolean

---@class PluginModule.Lazy
---@field event? string|string[]
---@field ft? string|string[]
---@field on_lsp_attach? string|string[]
